[package]
name = "protocols"
version = "0.1.0"
authors = ["Mike Leany <55358344+mikeleany@users.noreply.github.com>"]
edition = "2018"

[dependencies]
chess = { path = "../chess" }
log = "0.4.8"
regex = "1.3.1"
lazy_static = "1.4.0"
